In [1]:
# install torch and torchvision
#!pip install torch
# !pip install torchvision

In [2]:
import torch
import torchvision
import numpy as np

#Tensor

In [10]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data.shape)

torch.Size([2, 2])


In [9]:
x_nparray = np.array(data)
x_np  = torch.from_numpy(x_nparray)
print(x_np.shape)

torch.Size([2, 2])


In [13]:
# make tensor from shape of other tensor
x_ones  = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"\n ones tensor: \n {x_ones} \n random tensor : \n {x_rand}")


 ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 
 random tensor : 
 tensor([[0.1144, 0.8390],
        [0.5510, 0.7191]])


In [14]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [18]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}") 

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cuda:0


In [20]:
tensor = torch.rand(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([0.5612, 0.0423, 0.2094, 0.5880])
First column: tensor([0.5612, 0.3088, 0.3555, 0.7432])
Last column: tensor([0.5880, 0.3472, 0.2689, 0.9238])
tensor([[0.5612, 0.0000, 0.2094, 0.5880],
        [0.3088, 0.0000, 0.3841, 0.3472],
        [0.3555, 0.0000, 0.5838, 0.2689],
        [0.7432, 0.0000, 0.4361, 0.9238]])


In [24]:
t1 = torch.cat([tensor, tensor, tensor], dim= 1)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim =0)
print(t2)

tensor([[0.5612, 0.0000, 0.2094, 0.5880, 0.5612, 0.0000, 0.2094, 0.5880, 0.5612,
         0.0000, 0.2094, 0.5880],
        [0.3088, 0.0000, 0.3841, 0.3472, 0.3088, 0.0000, 0.3841, 0.3472, 0.3088,
         0.0000, 0.3841, 0.3472],
        [0.3555, 0.0000, 0.5838, 0.2689, 0.3555, 0.0000, 0.5838, 0.2689, 0.3555,
         0.0000, 0.5838, 0.2689],
        [0.7432, 0.0000, 0.4361, 0.9238, 0.7432, 0.0000, 0.4361, 0.9238, 0.7432,
         0.0000, 0.4361, 0.9238]])
tensor([[0.5612, 0.0000, 0.2094, 0.5880],
        [0.3088, 0.0000, 0.3841, 0.3472],
        [0.3555, 0.0000, 0.5838, 0.2689],
        [0.7432, 0.0000, 0.4361, 0.9238],
        [0.5612, 0.0000, 0.2094, 0.5880],
        [0.3088, 0.0000, 0.3841, 0.3472],
        [0.3555, 0.0000, 0.5838, 0.2689],
        [0.7432, 0.0000, 0.4361, 0.9238],
        [0.5612, 0.0000, 0.2094, 0.5880],
        [0.3088, 0.0000, 0.3841, 0.3472],
        [0.3555, 0.0000, 0.5838, 0.2689],
        [0.7432, 0.0000, 0.4361, 0.9238]])


In [30]:
# matrix multiplacation
y1 = tensor @ tensor.T
y2 = tensor.matmul( tensor.T)

print(y2)
print(y1)

# for element wise product 
z1  = tensor * tensor.T
z2  = tensor.mul(tensor.T)
print(f' \n z1 \n  {z1} \n z2 \n {z2}')

tensor([[0.7046, 0.4579, 0.4799, 1.0517],
        [0.4579, 0.3634, 0.4274, 0.7178],
        [0.4799, 0.4274, 0.5395, 0.7673],
        [1.0517, 0.7178, 0.7673, 1.5960]])
tensor([[0.7046, 0.4579, 0.4799, 1.0517],
        [0.4579, 0.3634, 0.4274, 0.7178],
        [0.4799, 0.4274, 0.5395, 0.7673],
        [1.0517, 0.7178, 0.7673, 1.5960]])
 
 z1 
  tensor([[0.3150, 0.0000, 0.0744, 0.4370],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0744, 0.0000, 0.3408, 0.1173],
        [0.4370, 0.0000, 0.1173, 0.8534]]) 
 z2 
 tensor([[0.3150, 0.0000, 0.0744, 0.4370],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0744, 0.0000, 0.3408, 0.1173],
        [0.4370, 0.0000, 0.1173, 0.8534]])


In [32]:
# single element tensor
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

5.710166931152344 <class 'float'>
