In [1]:
# learn tensor

In [2]:
import torch

In [6]:
# create an empty tensor

x = torch.empty(3)
print(x)
print(x.shape)
# create an empty tensor

x = torch.empty(3,2)
print(x)
print(x.shape)
# create an empty tensor

x = torch.empty(3,2,2,2)
print(x)
print(x.shape)
# create an empty tensor

# x = torch.empty(3)
# print(x)
# print(x.shape)

tensor([2.2717e+14, 3.0956e-41, 2.2743e+14])
torch.Size([3])
tensor([[ 2.2746e+14,  3.0956e-41],
        [ 2.2756e+14,  3.0956e-41],
        [-4.8627e-38,  4.5782e-41]])
torch.Size([3, 2])
tensor([[[[1.1035e-04, 4.5783e-41],
          [2.2710e+14, 3.0956e-41]],

         [[4.4842e-44, 0.0000e+00],
          [8.9683e-44, 0.0000e+00]]],


        [[[2.2710e+14, 3.0956e-41],
          [1.0779e-08, 2.4693e-18]],

         [[3.1360e+27, 7.0800e+31],
          [3.1095e-18, 4.7851e+22]]],


        [[[2.8826e+32, 4.4248e+30],
          [7.6729e+34, 2.1707e-18]],

         [[4.5447e+30, 7.0062e+22],
          [1.8077e-43, 0.0000e+00]]]])
torch.Size([3, 2, 2, 2])


In [16]:
# for tensor with random values 
x = torch.rand(2,2)
print(x)
# for tensor with ones , or zeros
x = torch.zeros(2,2)
print(x)
x = torch.ones(2,2)
print(x)

# the default data type is float32, 
print(x.dtype)

# to change the dtype
x  = torch.ones(2,2, dtype = torch.int) # dafault int is int32
# other data types: float, double, int
print(x)
print(x.dtype)


tensor([[0.2314, 0.3639],
        [0.5320, 0.4424]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
torch.float32
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32


In [20]:
# to show the size
print(x.size())

25
# to create a tensor of size
y = torch.tensor([3,3])
print(y)
print(y.size())
`

torch.Size([2, 2])
tensor([3, 3])
torch.Size([2])


In [26]:
# simple addition
x = torch.rand(2,2)
y= torch.rand(2,2)
print(f'x {x} \n y {y}')

# add
z = x+ y
print(f'z {z}')
z = torch.add(x,y)
print(f'z {z}')
# or inplace addition
y.add_(x)
print(y)
# _ means inplace operattion in pytroch
# similar with subract -> torch.sub
# element wise multiplication
# multiply = torch.mul
# y.mul_(x) # modifies y
# element wise division torch.div


x tensor([[0.0073, 0.0904],
        [0.8140, 0.4598]]) 
 y tensor([[0.3320, 0.8394],
        [0.6295, 0.5055]])
z tensor([[0.3392, 0.9298],
        [1.4435, 0.9654]])
z tensor([[0.3392, 0.9298],
        [1.4435, 0.9654]])
tensor([[0.3392, 0.9298],
        [1.4435, 0.9654]])


In [29]:
# slicing operation

x = torch.rand(5,3)
print(x)

# all rows one column 

y = x[:,0]
print(y)
# all columns one row 
y = x[1,:] # second row all columns
print(y)

tensor([[0.9457, 0.8556, 0.6469],
        [0.3041, 0.4620, 0.1428],
        [0.7240, 0.7126, 0.9158],
        [0.6749, 0.9813, 0.6501],
        [0.3922, 0.3081, 0.1561]])
tensor([0.9457, 0.3041, 0.7240, 0.6749, 0.3922])
tensor([0.3041, 0.4620, 0.1428])


In [36]:
# reshaping a tensor

x = torch.rand(5,6) 
print(x)
y = x.view(30) # one d vector 4*41
print(y)
y = x.view(-1,10)
print(y)

tensor([[0.5558, 0.9286, 0.8684, 0.6957, 0.6573, 0.4587],
        [0.2316, 0.5351, 0.5780, 0.6280, 0.8296, 0.5362],
        [0.3209, 0.3301, 0.4199, 0.6999, 0.3959, 0.9900],
        [0.3101, 0.8736, 0.1805, 0.3999, 0.3856, 0.2869],
        [0.9367, 0.4226, 0.5817, 0.9211, 0.8801, 0.6802]])
tensor([0.5558, 0.9286, 0.8684, 0.6957, 0.6573, 0.4587, 0.2316, 0.5351, 0.5780,
        0.6280, 0.8296, 0.5362, 0.3209, 0.3301, 0.4199, 0.6999, 0.3959, 0.9900,
        0.3101, 0.8736, 0.1805, 0.3999, 0.3856, 0.2869, 0.9367, 0.4226, 0.5817,
        0.9211, 0.8801, 0.6802])
tensor([[0.5558, 0.9286, 0.8684, 0.6957, 0.6573, 0.4587, 0.2316, 0.5351, 0.5780,
         0.6280],
        [0.8296, 0.5362, 0.3209, 0.3301, 0.4199, 0.6999, 0.3959, 0.9900, 0.3101,
         0.8736],
        [0.1805, 0.3999, 0.3856, 0.2869, 0.9367, 0.4226, 0.5817, 0.9211, 0.8801,
         0.6802]])


In [38]:
# tensors <---> numpy
import numpy as np

In [52]:
a =  np.ones(5)
b = torch.from_numpy(a)
print( a , b)
# if a gets changed  b would also be changed when they are on the processor . e.g gpu

a *= 2
print(a , b)
a = a * 3 
print(a , b)

# to change the tensor to gpu
a =  np.ones(5)
b = torch.from_numpy(a)

print( a , b)
b = b.to('cuda')
# if a gets changed  b would also be changed when they are on the processor . e.g gpu

a *= 2
a = a * 3 
print(a , b)

# to change the tensor to gpu


[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[6. 6. 6. 6. 6.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[6. 6. 6. 6. 6.] tensor([1., 1., 1., 1., 1.], device='cuda:0', dtype=torch.float64)


In [54]:
# when a tensor is created
x = torch.ones(5, requires_grad  = True)
print(x)
# this tells that the gradient needs to calculate in the optimzation steps
# whenever we want to optimize a vairable, we will use requires_grad = True

tensor([1., 1., 1., 1., 1.], requires_grad=True)
