In [2]:
# how to use autograd in torch to calculate gradient

import torch

In [3]:
x = torch.rand(3)
print(x)

tensor([0.4439, 0.4057, 0.6275])


In [13]:
# now we need to calculate the gradient of a funciton wrt x

x = torch.rand(3, requires_grad= True)
print(x)

tensor([0.8393, 0.6790, 0.5973], requires_grad=True)


In [65]:
x = torch.rand(3, requires_grad= True)

print(x)
print(x*2)
y = x+2
# this creates a computational graph , here the operation is + 
'''
 x ------\
        (+) ----- y
         /
 2 -----

'''
# this function is used for backpropgation
print(y)
# we can see the grad_fn with add backward0  which mea
z = y *y* 2
print(z)
# here the operation is multiplaction we can see the MULbackward0 
z = z.mean()
print(z)
# similarly a the meanBackward function
z.backward()
print(x.grad)

tensor([0.7882, 0.1970, 0.8241], requires_grad=True)
tensor([1.5764, 0.3941, 1.6482], grad_fn=<MulBackward0>)
tensor([2.7882, 2.1970, 2.8241], grad_fn=<AddBackward0>)
tensor([15.5480,  9.6539, 15.9510], grad_fn=<MulBackward0>)
tensor(13.7176, grad_fn=<MeanBackward0>)
tensor([3.7176, 2.9294, 3.7655])
